name: ADF Pipeline
on:
  workflow_dispatch:
    inputs:
      ENV:
         required: true
         type: string
  push:
    branches:
       - "adf_publish"
jobs:
  deploy-adf:
    name: Deploy Azure Data Factory
    environment: uat
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Update factoryName in parameters file
        run: |
          sed -i "s/\"factoryName\": {\\n\\s*\"value\": \".*\"/\"factoryName\": {\n            \"value\": \"${{ vars.ADF_NAME }}\"/" ./sep24exercise2/ARMTemplateParametersForFactory.json
          cat ./sep24exercise2/ARMTemplateParametersForFactory.json

      # Step 2: Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Deploy ARM Template
      - name: Deploy ADF Resources
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: 'RG1TestGroup'
          template: './sep24exercise2/ARMTemplateForFactory.json'
          parameters: './sep24exercise2/ARMTemplateParametersForFactory.json'
          deploymentMode: Incremental
